/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mendinterview;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        GraphController classUnderTest = new GraphController();
        //assertNotNull(classUnderTest.calculateShortestPaths(), "app should have a greeting");
    }
}
